packages:
  - "projects/*"

catalog:
  # React
  "react": "^18.3.1"
  "react-dom": "^18.3.1"
  "react-router": "^6.26.0"
  "react-router-dom": "^6.26.0"
  "@remix-run/router": "^1.19.0"
  "@types/react": "^18.2.66"
  "@types/react-dom": "^18.2.22"
  "scheduler": "^0.23.2"
  "jsdom": "^24.1.1"
  "@testing-library/react": "^16.0.0"
  # Typescript
  "@types/node": "^22.0.0"
  "typescript": "^5.5.3"
  "tsx": "^4.16.0"
  # Vite
  "vite": "^5.4.0"
  "vite-tsconfig-paths": "^4.3.2"
  "vitest": "^2.0.4"
  "@vitejs/plugin-react": "^4.2.1"
  # Lintter
  "@biomejs/biome": "1.9.2"
  # Others
  "husky": ^9.1.4
  "globals": "^15.11.0"
